version: '3.8'

services:
  web:
    build: .
    container_name: python_web_app
    ports:
      - "8081:5000"
    # environment:
    #   DB_HOST: db
    #   DB_USER: myuser
    #   DB_PASSWORD: mypassword
    #   DB_NAME: mydatabase
    volumes:
      - .:/usr/src/app

volumes:
  mysql_data: